project_id = "dhjvxtwflntmvbzkqsjn"

[functions.ask-ai]
verify_jwt = true

[functions.gemini-chat]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.maritime-news]
verify_jwt = false